#!/bin/sh

HOMEBREW_PREFIX=$(brew --prefix)

OPENSSH_SERVICE_SOCK=${OPENSSH_SERVICE_SOCK:=/tmp/openssh-service.socket}
# This script is used to start brew ssh-agent as a service on macOS
# Can also be used for variety of diagnostics and troubleshooting

log() {
  echo "$(date '+%F %T.%N') $1"
}

usage() {
  echo "Usage: $0 <help|check|run|session|launchd>"
  echo "  help: Print this help message"
  echo "  check: Returns the status of the service"
  echo "  run: Simply run the service manually"
  echo "  eval: Source this eval \$($0 eval), to set the SSH_AUTH_SOCK in current session"
  echo "  logpath: return the path of the logfile, if started with launchd"
  echo "  launchd: Special for launchd, do not use"
}

check() {
  brew services info openssh-service 1> /dev/null 2> /dev/null

  if [ $? -ne 0 ]; then
    echo "Service not installed"
    echo "You need to execute 'brew services start openssh-service' to configure the service to start at login"
    exit 1
  elif [ "$(brew services info openssh-service --json | jq '.[].running')" == "false" ]; then
    echo "Service installed but not running."
    echo "Have a look at openssh-service in system.log for more information"
    exit 1
  elif [ "$SSH_AUTH_SOCK" != "$OPENSSH_SERVICE_SOCK" ]; then
    echo "Service running (PID=$(brew services info openssh-service --json | jq '.[].pid')) but not configured in this session."
    echo "If you haven't configured the agent in ~/.ssh/config,"
    echo "You can run 'eval \$($0 eval)' to configure in this session"
    echo "Logfile: $(brew services info openssh-service --json | jq -r '.[].log_path')"
  else
    echo "Service running (PID=$(brew services info openssh-service --json | jq '.[].pid')) and configured in this session."
    echo "Logfile: $(brew services info openssh-service --json | jq -r '.[].log_path')"
  fi
}

run() {
  export SSH_ASKPASS="$HOMEBREW_PREFIX/bin/ssh-askpass"
  export SSH_ASKPASS_REQUIRE=force
  export DISPLAY=":0"
  log Running ssh-agent with the following environment variables:
  log SSH_ASKPASS=$SSH_ASKPASS
  log SSH_ASKPASS_REQUIRE=$SSH_ASKPASS_REQUIRE

  $HOMEBREW_PREFIX/bin/ssh-agent -D -a $OPENSSH_SERVICE_SOCK
}

launchd() {
  log "Set system environment variable OPENSSH_SERVICE_SOCK to $OPENSSH_SERVICE_SOCK"
  launchctl setenv OPENSSH_SERVICE_SOCK $OPENSSH_SERVICE_SOCK
  run
}

sessioneval() {
  SOCK=$(launchctl getenv OPENSSH_SERVICE_SOCK)
  if [ -z "$SOCK" ]; then
    SOCK=$OPENSSH_SERVICE_SOCK
  fi
  echo "export OPENSSH_SERVICE_SOCK=$SOCK;export SSH_AUTH_SOCK=$SOCK;"
}

logpath() {
  echo $(brew services info openssh-service --json | jq -r '.[].log_path')
}

if [ $# -lt 1 ]; then
  usage
  exit 1
elif [ "$1" == "help" ]; then
  usage
elif [ "$1" == "check" ]; then
  check
elif [ "$1" == "run" ]; then
  run
elif [ "$1" == "launchd" ]; then
  launchd
elif [ "$1" == "eval" ]; then
  sessioneval
elif [ "$1" == "logpath" ]; then
  logpath
fi
